### ISSUE TITLE
More famous / predefined systems

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/DynamicalSystemsBase.jl#111]
http://www.3d-meier.de/tut19/Seite0.html 

Has pictures as well, some are super cool.

**Comment by KalelR** [comment]
Hey, I'm new here, but I'd like to start contributing :) 
From the link you suggested and also from [this list in Wikipedia](https://en.wikipedia.org/wiki/List_of_chaotic_maps), I'd suggest these models:

Continuous:
1. Hodgkin-Huxley
2. Hindmarsh-rose
3. Van der Pol oscillator
4. Lotka-volterra model
5. Maybe the normal forms of bifurcations. For the Hopf bifurcation, this is also known as the Stuart-Landau oscillator.

Discrete:
1. Tent map
2. Beta transformation (which includes the dyadic transformation aka Bernouli map aka 2x mod 1 map)
3. Rulkov map
4. Ikeda map

Some of them are very simple, but they are all famous.

What do you think? I can implement these and do a pull request.

**Comment by Datseris** [comment]
Sounds good to me, and happy to see new contributors!!! We don't have lotka-volterra? damn that's embarrasing...

**Comment by Datseris** [comment]
> Maybe the normal forms of bifurcations. For the Hopf bifurcation, this is also known as the Stuart-Landau oscillator.

Ah, but this no :P
