### ISSUE TITLE
Unexpected behavior for Stroboscopic Maps integrator

### ISSUE THREAD

**Issue by awage** [JuliaDynamics/DynamicalSystemsBase.jl#139]
While debugging the test suite for the Duffing stroboscopic map I found this curious problem: 

```julia
    ds = Systems.duffing([0.1, 0.25]; ω = 1.0, f = 0.2, d = 0.15, β = -1)
    diffeq = (alg = Vern9(), reltol = 1e-9, abstol = 1e-9)
    T = 2π/1.0
    smap = stroboscopicmap(ds, T; diffeq)
    u = [ -1.1138050859103932; -2.1479938326919292]
    reinit!(smap , u)
    for k = 1:100 
           step!(smap)
    end
    get_state(smap)
  
   reinit!(smap , u)
   step!(smap,100)
   get_state(smap)
```

The results are different: 

2-element SVector{2, Float64} with indices SOneTo(2):
 -0.7790549287373568
  0.027416815463530947

2-element SVector{2, Float64} with indices SOneTo(2):
 1.2100908250696358
 0.05529496614789722

@Datseris: Do you have any clue? It is the reason why the basin fractions are different for the mapper by Proximity and the mapper by Recurences.

**Comment by Datseris** [comment]
damn, we'll have to dig deep. One thing I suspect is the time zero, what `t` is when things are reinited. Is t become the same thing in both cases?

**Comment by awage** [comment]
The initial times are 0 in both cases. There are very small numerical errors accumulating. We are seeing chaos at work: 

![imagen](https://user-images.githubusercontent.com/3494384/159462958-74368331-8c7c-47a3-af02-c37cea2bc7f0.png)

Obtained with: 

```julia
t1 = []
reinit!(smap , u)
for k = 1:100 
   push!(t1, get_state(smap))
   step!(smap)
end
t1 = Dataset(t1)

t2 = trajectory(ds, 100*T, u; Δt = T, diffeq )
plot(t1[:,1])
plot!(t2[:,1])
```

It is not a big deal if you use two different methods. But the `step!` functions of the `StroboscopicMap` should give the same results for coherence. The trick would be to change this: 

```julia
function step!(smap::StroboscopicMap, n::Int)
	step!(smap.integ, n*smap.T, true)
	return smap.integ.u
end
``` 

for 

```julia
function step!(smap::StroboscopicMap, n::Int)
	for k in 1:n; step!(smap.integ, smap.T, true); end
	return smap.integ.u
end
```

**Comment by Datseris** [comment]
I agree. Could you please do a quick PR to change the method to the second version?
