### ISSUE TITLE
Cannot use trajectory with simple non-adaptive solver types

### ISSUE THREAD

**Issue by rusandris** [JuliaDynamics/DynamicalSystemsBase.jl#151]
Currently there is an initialization error when one tries to use `trajectory` with simple solvers other than `SimpleATsit5` (the default).   
```julia
using DynamicalSystems
ds = Systems.lorenz()
trajectory(ds,100;diffeq = (alg = SimpleTsit5(), dt=1e-2))
```

The error message:
```julia
ERROR: MethodError: no method matching __init(::SciMLBase.ODEProblem{SVector{3, Float64}, Tuple{Float64, Float64}, false,
Vector{Float64}, SciMLBase.ODEFunction{false, SciMLBase.AutoSpecialize, typeof(DynamicalSystemsBase.Systems.loop), 
LinearAlgebra.UniformScaling{Bool}, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing,
 Nothing, Nothing, typeof(SciMLBase.DEFAULT_OBSERVED), Nothing, Nothing}, Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(),
 Tuple{}}}, SciMLBase.StandardODEProblem}, ::SimpleTsit5; abstol=1.0e-6, reltol=1.0e-6, save_everystep=false, alg=SimpleTsit5(), 
dt=0.01)

Closest candidates are:
  __init(::SciMLBase.ODEProblem, ::SimpleTsit5; dt) at ~/.julia/packages/SimpleDiffEq/72VGn/src/tsit5/tsit5.jl:29
 got unsupported keyword arguments "abstol", "reltol", "save_everystep", "alg"

```
Same with `SimpleRK4`. Probably the default keyword arguments aren't compatible with these types.

**Comment by Datseris** [comment]
Yeah I think you are right. I guess we have to make the default keywords not passed when a user specifies the solver!

**Comment by xlxs4** [comment]
So a check to see if [`solver`](https://github.com/JuliaDynamics/DynamicalSystemsBase.jl/blob/main/src/core/continuous.jl#L55) is the [`DEFAULT_SOLVER`](https://github.com/JuliaDynamics/DynamicalSystemsBase.jl/blob/main/src/core/continuous.jl#L9) and if not, call [`__init`](https://github.com/JuliaDynamics/DynamicalSystemsBase.jl/blob/main/src/core/continuous.jl#L56) without passing [`DEFAULT_DIFFEQ_KWARGS`](https://github.com/JuliaDynamics/DynamicalSystemsBase.jl/blob/main/src/core/continuous.jl#L10), `save_everystep` and `diffeq`?

**Comment by Datseris** [comment]
yes.

**Comment by xlxs4** [comment]
Something along the lines of
```julia
if solver == DEFAULT_SOLVER
    integ = __init(prob, solver; DEFAULT_DIFFEQ_KWARGS...,
                   save_everystep = false, diffeq...)
else
    integ = __init(prob, solver)
end
```

fares fine, but, for example, `SimpleTsit5()` [requires](https://github.com/SciML/SimpleDiffEq.jl/blob/master/src/tsit5/tsit5.jl#L30) `dt` to be passed, so it still won't work. [Same](https://github.com/SciML/SimpleDiffEq.jl/blob/master/src/rk4/rk4.jl#L37) with `SimpleRk4`. They don't support an `alg` argument though, while currently one needs to pass `diffeq = (alg = SimpleTsit5(), dt=1e-2))` to `trajectory`. Any pointers?

**Comment by Datseris** [comment]
> They don't support an alg argument though

I don't understand what this means.

**Comment by Datseris** [comment]
```julia
else
    integ = __init(prob, solver)
end
```
this doesn't make sense, because it doesn't use `diffeq...` which are the arguments the user actually wants to use.

**Comment by xlxs4** [comment]
Yes, if we do
```julia
else
    integ = __init(prob, solver; diffeq...)
end
```

Then in the example above, `alg` will be passed as a keyword argument to `SimpleTsit5`'s [`__init`](https://github.com/SciML/SimpleDiffEq.jl/blob/master/src/tsit5/tsit5.jl#L29), resulting in a `MethodError`.

**Comment by xlxs4** [comment]
For example, 
```julia
integ = __init(prob, solver; dt = diffeq[:dt])
```
would work with both `SimpleTsit5` and `SimpleRk4`. This seems a bit hacky to me though, that's why I'm asking.

**Comment by Datseris** [comment]
Oh, now I understand. Okay, the solution is that you must _remove_ `alg` from the `diffeq` keywords and pass the remaining keywords.

**Comment by Datseris** [comment]
Actually, I'm surprised we weren't doing this all this time.... so stupid oh god how did i not see this all these years. When we do:
```
solver = _get_solver(diffeq)
```

we instead must do:
```
solver, remaining = decompose_into_solver_and_remaining(diffeq)
```

**Comment by Datseris** [comment]
and pass `remaininng` to `__init` instead of `diffeq`.

**Comment by xlxs4** [comment]
I get that a `NamedTuple` might not be ideal for this (?)
Maybe something like:
```julia
function decompose_into_solver_and_remaining(diffeq)
    function naive_decompose_tuple(tuple, key::Symbol)
        out = []
        for sym in propertynames(tuple)
            if sym != key
                push!(out, getproperty(tuple, sym))
            end
        end
        return (getproperty(tuple, key), Tuple(out))
    end

    if haskey(diffeq, :alg)
        return naive_decompose_tuple(diffeq, :alg)
    else
        return (DEFAULT_SOLVER, diffeq)
    end
end
```

**Comment by Datseris** [comment]
You can use named tuples: https://github.com/JuliaLang/julia/issues/27574#issuecomment-397838647
