### ISSUE TITLE
`poincaresos` for datasets no longer works with vector-typed hyperplane 

### ISSUE THREAD

**Issue by rusandris** [JuliaDynamics/DynamicalSystemsBase.jl#179]
It seems there's a bug somewhere with the namespaces/dependencies.
MWE:

```julia
ds = PredefinedDynamicalSystems.lorenz()
traj, = trajectory(ds,50000;Ttr=1000)

poincaresos(traj,(1,15.0)) #works
poincaresos(traj,[1,0,0,15.0]) #doesn't work
```
Last function call gives the following error:
`ERROR: UndefVarError: LinearAlgebra not defined`
encountered when calling 
`
 [1] interpolate_crossing(A::SVector{3, Float64}, B::SVector{3, Float64}, pc::PlaneCrossing{Vector{Float64}, 3, Float64})
`

The weird thing is
```julia
poincaresos(ds,(1,15.0))
poincaresos(ds,[1,0,0,15.0])
```
both work.

`Julia Version 1.9.2` and `DynamicalSystemsBase v3.2.1`

**Comment by Datseris** [comment]
easy fix, add `using LinearAlgebra` before the function `interpolate_crossing` in the source code!
