### ISSUE TITLE
DeterministicIteratedMap not being exported properly

### ISSUE THREAD

**Issue by hinsley** [JuliaDynamics/DynamicalSystemsBase.jl#207]
**Describe the bug**
`DeterministicIteratedMap` does not seem to be getting exported properly. From the MWE, I get the following error:

```julia
ERROR: UndefVarError: `DeterministicIteratedMap` not defined
Stacktrace:
 [1] top-level scope
   @ Untitled-1:13
```

**Minimal Working Example**
```julia
using DynamicalSystems

function f_rule(u, p, n)
    x = u[1]
    a = p[1]
    fx = min(a*x^2+x, a*x^2-(2*a+1)*x+a+1)
    return fx
end

u0 = [0.5]
p0 = [1]

f = DeterministicIteratedMap(f_rule, u0, p0)
```

**Package versions**

DynamicalSystems v2.3.2
Julia v1.10

**Comment by Datseris** [comment]
You reported DynamicalSystems v2.3.2 but latest stable version is 3.3.11. You're years behind in the version. When visiting the docs please look in the bottom left of the page to see the version

![image](https://github.com/JuliaDynamics/DynamicalSystemsBase.jl/assets/19669089/c75ddd2c-b606-498a-91bb-cc1b748822f0)
