### ISSUE TITLE
Which type of interpolation for poincare section of state space set?

### ISSUE THREAD

**Issue by JonasKoziorek** [JuliaDynamics/DynamicalSystemsBase.jl#218]
Can you explain further?

https://github.com/JuliaDynamics/DynamicalSystemsBase.jl/blob/8cc1b54f1b78b9d570f47d8cd0366b19606c332d/src/derived_systems/poincare/hyperplane.jl#L73-L74

Do you want [polynomial interpolation](https://en.wikipedia.org/wiki/Polynomial_interpolation) or [spline interpolation](https://en.wikipedia.org/wiki/Spline_interpolation)?

**Comment by Datseris** [comment]
I meant cubic spline interpolation.
