### ISSUE TITLE
Add `Reconstruction` method for spatio-temporal embedding

### ISSUE THREAD

**Issue by JonasIsensee** [JuliaDynamics/DynamicalSystemsBase.jl#47]
For prediction of spatio-temporal timeseries a special type of delay embedding is necessary as descibed in [1].
The embedding should work like this:
![screenshot from 2018-03-20 13-09-54](https://user-images.githubusercontent.com/33990604/37653697-03fa77e8-2c40-11e8-822a-6d00af603afe.png)

The call signature could look like this:
`Reconstruction(s,D,τ,I,K, c)`
where `D` and `τ` delay and (delay-) dimension as usual.. `I` is the number of spatial neighbors and `K` the
spatial shift.
`c` is used for boundary conditions as visualized in the picture. If a proper default value can be found this could be made an optional kwarg.

[1] U. Parlitz, *Prediction of Spatiotemporal Time Series Bases on Reconstructed Local States* (2000)

**Comment by Datseris** [comment]
I am not so sure about whether this should be implemented as a feature of the package. It is really pushing stuff in the limit of doing everything for the user and the user doing nothing.

It is already possible (and in my eyes quite easy) to do what you are reporting:

1. The user can successively choose the columns of this matrix and reconstruct them individually. Let's say he chooses columns 4,5,6 corresponding to `I = 1, K = 1`.  Another example would be choosing `N-1, N, c`. The reconstruct this dataset with `D, τ`.

2. Then predict this dataset. Then, choose the midle column of the prediction as the timeseries to keep as a prediction. This is the prediction of the spatiotemporal column `5`.

3. Repeat the process for all columns.

Can you show whether there is any gain in implementing what you suggest as a feature of the package?

(yes I know that you have to do it irrespectively for your thesis)

**Comment by Datseris** [comment]
I think we have to be careful so that the packages make it easy for users to do science, but don't do the science for them.

This can be risky.
