### ISSUE TITLE
Change parallel_integrator to always have matrix for continuous systems?

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/DynamicalSystemsBase.jl#53]
Should we change (for performance benefits) the parallel integrator of continuous systems to always use a matrix with `hcat` states?

Maybe the internals of DifferentialEquations.jl do not optimize very well vectors of vectors as state...???

```julia
# Initialize the lorenz system with random initial condition
lor = Systems.lorenz()

Q0 = eye(3)

btime lyapunovs($lor, 2000, $Q0; Ttr = 10.0);

  121.728 ms (270 allocations: 30.73 KiB)

@btime lyapunov($lor, 2000; Ttr = 10.0);

  161.619 ms (408 allocations: 33.38 KiB)
```

@ChrisRackauckas maybe this is interesting for you, so I'll give you some context. `lyapunovs` evolves a 3x4 matrix (12 elements) and does a QR decomposition 2000 times. The equations of motion is 1 application of the lorenz system and 1 application of the jacobian (matrix multiplication). **The state of the system in this case is a 3x4 SMatrix**.

`lyapunov` evolves a Vector of 2 SVectors. The equations of motion are 2 applications of the lorenz system, which I assume to be more slow than 1 lorenz and 1 jacobian. However, no QR decomposition is done, only a trivial distance computation. **The state of the system in this case is a Vector{SVector}**

I know that `QR` from StaticArrays is super fast:
```
s = rand(SMatrix{3,3})
@btime qr($s)

  51.059 ns (0 allocations: 0 bytes)
```
but I would still assume `lyapunovs` to be slower than `lyapunov`!!!
When doing 
```
@profiler lyapunovs(lor, 2000, Q0; Ttr = 10.0);
```
```
@profiler lyapunov(lor, 2000.0; Ttr = 10.0);
```
in Juno, I can see that in both cases "all" time seems to be spent on `perform_step!` and `loopfooter!` so I can't really tell if this is an issue from DifferentialEquations.jl or from me. If you need more info let me know. But don't be alarmed... In the end of the day it may just be that the QR of static arrays for 3x3 is so damn fast that it is faster to evolve the tangent space than evolving 2 "normal" trajectories.

**Comment by ChrisRackauckas** [comment]
>I can see that in both cases "all" time seems to be spent on perform_step! and loopfooter! so I can't really tell if this is an issue from DifferentialEquations.jl or from me.

If your `f` function is really well optimized then that's what you'll see. Basically, it spends so little time doing the actual computation that it picks up the two floating point `^` calculations in the loopfooter as significant (this is actually fixed on Julia v0.7 BTW where `^` is about 4x faster, but it's still a fun detail). Vector of SVector should be pretty well-optimized, so this is likely due to that QR being super good. The one from the tangent bundle may be taking larger steps too.
