### ISSUE TITLE
Inconsistency for MTDelayEmbedding

### ISSUE THREAD

**Issue by JonasIsensee** [JuliaDynamics/DynamicalSystemsBase.jl#73]
Hey!

I'm trying to fix all my test cases to your D → D+1 change with the number of neighbors.
Why did you want to do this again? I find it super confusing that `D` is used as number
of neighbors `D` and as type parameter `D=D+1` as well.

Anyway, there seems to be an inconsistency as
`MTDelayEmbedding` needs `D = 4`
 for ` τ=[0 0; 15 15; 30 29; 45 45]`
Even though there are only three actual neighbors.

**Comment by JonasIsensee** [comment]
My bad. Never mind.
Problem solved. Confusion remains.

**Comment by Datseris** [comment]
Huh. Can you explain the confusion again? At the moment on DynSysBase, globally, everywhere `D` stands for the number of temporal neighbors. Doesn't matter if it is argument or type parameter...

We both agreed to do this while you were in my office!!!

**Comment by Datseris** [comment]
that is why I have this weird `gensprev` 
```
    gensprev = [:(s[i, $d]) for d=1:B]
    gens = [:(s[i + r.delays[$k, $d], $d]) for k=1:D for d=1:B]
    quote
        @_inline_meta
        @inbounds return SVector{$(D+1)*$B,T}($(gensprev...), $(gens...))
    end
end
```
so that indeed D is the number of temporal neighbors. You can also see it from the return statement that has `SVector{D+1..}`

**Comment by Datseris** [comment]
Notice: in the current setup you never pass 0 to the taus... The 0 is added by the struct.

**Comment by JonasIsensee** [comment]
The issue and my confusion comes from the following:
You write `SVector{D+1, T}` when creating the SVector which is fine.

I on the other hand get the SVectors as arguments.
`f(x::SVector{D+1, T}) where {D,T}` is impossible.
Instead I have to introduce another name
```
f(x::SVector{DD, T} where {DD,T}
   D = DD - 1
   ...
```
whose only purpose is to subtract 1 from it.

**Comment by Datseris** [comment]
Oh you mean in Timeseries Prediction??????? Damn yeah I didn't think about it.

Do you want to modify the `DelayEmbedding` struct to have one extra type parameter `L` which will be `D+1`? That will make everything clearer!

**Comment by JonasIsensee** [comment]
I will think about it. I don't work with your `DelayEmbedding` directly because I just call your `reconstruct` function in the non-spatial case.

`LinearLocalModel` used to get parameter `D` from the SVector:
```function (M::LinearLocalModel)(
    q,
    xnn::Vector{SVector{D,T}},
    ynn::Vector{SVector{D,T}},
    dists) where {D,T}```

**Comment by Datseris** [comment]
Yes in the latter case it makes sense to have the extra parameter `L`. By the way the change we are discussing takes at best 5 minutes.

**Comment by JonasIsensee** [comment]
No need to rush this. `LinearLocalModel` doesn't know the `DelayEmbedding` struct anyway.
For now we can get away with renaming the type parameter inside that function.

I will make a PR if I stumble upon it again

**Comment by Datseris** [comment]
Be sure to check for type stability when doing this. Doing `DD = D+1` works at compile time, but I am not sure whether it is type stable at run time.
