### ISSUE TITLE
Minimal and self-contained integrator with only basic features [$100]

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/DynamicalSystemsBase.jl#76]
# Goal
We request a minimal and self-contained integrator for systems of ODEs. This could be added here, but it makes much more sense for it to be in `SimpleDiffEq` repo. This issue is here for the bounty.

This minimal integrator, because it will _not_ have most of the features of a standard DiffEq integrator, will be faster to compile and maybe faster to run as well. Who knows... But, besides any performance benefits, it will have educational value. A principal of **DynamicalSystems.jl** is that "you know whats going on", and a simple integrator with only a couple of `.jl` files will make this easier.

Our main goal is twofold:
1. Reduce the "time until first result", which is mostly compilation.
2. Make something that is easy to read and easy to understand.

# Detailed Description

We want a continuous system ODE solver that has the following properties:

1. Extends `init` from `DiffEqBase` to create/initialize the integrator object given an `ODEProblem`.
2. Extends `step!` from `DiffEqBase` to "step" the integrator for one step. Adaptive stepping and error checking must be included.
3. It **must not** support callbacks, event handling, etc.
4. It **must not** support storing / creating a solution object. We will be exclusively using `step!`. Only the previous state and current state need to be stored.
6. It must support both in-place and out-of-place type of equations of motion (see diff eq for more).
7. It must support the following three types of states: Vector of numbers, Vector of Vectors (both `Vector` and `SVector`) and Matrix. Notice that for state-type VectorOfVectors only in-place version is necessary. With this I mean that it doesn't matter if the state is `Vector{Vector}` or `Vector{SVector}`, the _outer_ vector is modified always in-place. For the other two cases both in-place (`Vector/Matrix {Number}`) and out-of-place (`SVector/SMatrix {Number}` ) are necessary.
8. It must support interpolation in between the previous and current state. The code from `OrdinaryDiffEq` does this already.
9. It must support "setting"/"changing" the current state. This allows not only `reinit!` but also allows one to change the state during integration which is crucial for JuliaDynamics.
8. You are also very welcomed to cut high-level features like allowing a distribution as initial state, etc.

You can choose whichever you want DOPRI5/Verner9 (I vote for Verner9 but who am I). 
I am suggesting those two so you can actually copy the code that @ChrisRackauckas has pasted there, and have the least effort for this issue. Please try to copy as much from the actual `step!` implementation of OrdinaryDiffEq as possible, since it is highly optimized. This is open source in the end, just be sure to copy the license ;)

# The Bounty

The 100$ bounty of this issue is posted by user @Datseris , a member of JuliaDynamics. @Datseris _does not_ have merge or admin privileges to repositories of the DiffEq org. Once the integrator is merged you can do a one-liner PR here that changes the default integrator to the one you contributed. Even if the integrator is not accepted by DiffEq but it is accepted in JuliaDynamics, you can still move it here and you will get the bounty.

**Comment by ChrisRackauckas** [comment]
@yingboma
