### ISSUE TITLE
Specific version requirement causes dependency error

### ISSUE THREAD

**Issue by JonasIsensee** [JuliaDynamics/DynamicalSystemsBase.jl#88]
```
[compat]
DiffEqBase = "5.10.0"
```
This is a very specific version requirement. ( Current version is 6.2.3 or so)
Can this be relaxed? It causes dependency errors when trying to install
it on julia 1.2. (`DifferentialEquations.jl` was added beforehand)

**Comment by Datseris** [comment]
There was an update in DiffEqBase 6.0, which causes errors. @asinghvi17 reported this on Slack. I don't know the current status, maybe someone wants to update the code? Shouldn't be hard.

**Comment by asinghvi17** [comment]
The issue was actually the bounds, sorry if I wasn't clear - the dependency errors were the issue.

**Comment by Datseris** [comment]
Is there still an issue or not?

**Comment by JonasIsensee** [comment]
I believe @asinghvi17 meant to say that there is only one problem which is
the dependency error I mentioned above.

**Comment by asinghvi17** [comment]
FWIW, if I remove the compat entries, with DiffEqBase at 6.2.0, tests pass on ChaosTools and DynamicalSystemsBase.
