### ISSUE TITLE
Allow Matrix-based equations of motion

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/DynamicalSystemsBase.jl#9]
Straight forward issue, easy to implement but unfortunately one has to write many lines of code! 🗡 

This allows to passing matrix-valued `ODEProblem` as well.

**Comment by ChrisRackauckas** [comment]
just put `vec` on a bunch of things.

**Comment by Datseris** [comment]
Oh yea, forgot about `vec`. This is not allocating right? It will make solving this issue very straightforward I think.

**Comment by ChrisRackauckas** [comment]
Yes, it's just a view which changes the indexing (well, gets rid of the extra indexing stuff actually).

**Comment by Datseris** [comment]
This wont be supported (at least by me)
