### ISSUE TITLE
Allow indexing datasets with vector{Bool}

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/DynamicalSystemsBase.jl#91]
At the moment something as simple and as convenient as
```julia
using DynamicalSystems
lor = Systems.lorenz()
tr = trajectory(lor, 100.0, dt = 0.01, Ttr = 50.0)
x, y, z = columns(tr)
behind = tr[y .< 0, :]
```
does not work, but is quite simple to implement

**Comment by yuxiliu1995** [comment]
Isn't this closed by https://github.com/JuliaDynamics/DelayEmbeddings.jl/commit/20c94f63fc298ad7614fc9d1bbe303fb46c7a0a4
