### ISSUE TITLE
system with matrix state not abstract vector

### ISSUE THREAD

**Issue by SidxA** [JuliaDynamics/DynamicalSystemsBase.jl#96]
Hello,
defining a constructor for a 3 dimensional System with possibilty to extend by coupling

```
function algeb_evol!(dr,r,p,t)
    u = @view r[:,1]  
    v = @view r[:,2]  
    w = @view r[:,3]  
    du = @view dr[:,1]  
    dv = @view dr[:,2]  
    dw = @view dr[:,3]  
    @. du = 1 * u - 0.2 * u * v / (1 + 0.05 * u)  
    @. dv = - 0.98 * v + 0.2 * u * v / (1 + 0.05 * u) - 1 * v * w   
    @. dw = - 10 * (w - 0.006) + 1 * v * w  
end
```

with initials
`A = zeros(Int8,2,2)`
`r0 = [[9.0,10] [8.1,5] [0.6,0.5]]`
and Calling `ds = ContinuousDynamicalSystem(algeb_evol!,r0,nothing)`
gives 

`ArgumentError: The state of a dynamical system *must* be <: AbstractVector/Number!
`

@ChrisRackauckas and @Datseris mentioned trying to put a vector around it at the [discourse](https://discourse.julialang.org/t/regime-estimation-for-parameter-space-of-small-system/41588/3)

**Comment by ChrisRackauckas** [comment]
The internal tools just need to `vec` where ever they assume the value is vector.

**Comment by Datseris** [comment]
Wait a moment. @SidxA in this example the state of your dynamical system is a **matrix** or a vector of vectors, right? its not that you use views that is the problem.

**Comment by ChrisRackauckas** [comment]
>The reason we need states as vectors is because of the tangent space integrator, which creates a new system, whose state is a matrix, and the first column of the matrix is a the state of the system.

It is possible. Higher dimensional arrays are just vectors with fancy indexing. Just tell the tools that want a vector that it's a vector and you're good.

**Comment by ChrisRackauckas** [comment]
>The user-provided f function can always return a vector itself, and I see this as the best workaround at the moment.

Yes, this is just the inverse of the relation. Vectors and matrices are the same thing in memory, so `reshape` is free and you can use that in a user code to make a vector index like a matrix or higher order tensor.

**Comment by SidxA** [comment]
Well the point of this matrix was not to care about the number of dimensions.
When I put everything into one vector and reshape it all the time(implemented for arbitrary dimensions),
doesnt it take a lot of calculation to realocate at every call?

**Comment by Datseris** [comment]
It doesn't cost anything computation wise, because matrices can be transformed to vectors without cost. But I absolutely agree that it is tedious to do it on the user side, and should definitely be done on the side of DynamicalSystems.jl. Unfortunately I don't know how long this will take, as it is quite some effort to do this, and I am currently the only maintainer of the library, so I typically prefer spending time on new algorithms :(

**Comment by SidxA** [comment]
As I intend to scale up the dimension, I guess it makes no sense to stack-allocate and
just leave it with explicit dimensionnumber as

> function vec_evol!(dr,r,p,t)
>     d = p[1]
>     A = p[2]
>     u = @view r[1:d]
>     v = @view r[d+1:2d]
>     w = @view r[2d+1:3d]
>     du = @view dr[1:d]
>     dv = @view dr[d+1:2d]
>     dw = @view dr[2d+1:3d]
>     @. du = 1 * u - 0.2 * u * v / (1 + 0.05 * u)
>     @. dv = - 1 * v + 0.2 * u * v / (1 + 0.05 * u) - 1 * v * w 
>     @. dw = - 10 * (w - 0.006) + 1 * v * w
>     dv += 0.2 .* sum((A .* v) .- transpose(A.*v),dims=2)
>     dw += 0.2 .* sum((A .* w) .- transpose(A.*w),dims=2)
> end

Everything works with that and the performance is relatively okay.
Thanks for keeping such a great project up yourself.
